# Generated by Django 5.0.1 on 2025-10-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('service_type', models.CharField(choices=[('court_disputes', 'Суды и Споры'), ('business_registration', 'Регистрация бизнеса'), ('contracts', 'Договоры'), ('business_support', 'Сопровождение Бизнеса'), ('project_organization', 'Организация проектов и фестивалей'), ('personal_injury', 'Личная травма')], max_length=50, verbose_name='Тип услуги')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос на консультацию',
                'verbose_name_plural': 'Запросы на консультацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
